# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'council member',
            },
        ),
        migrations.CreateModel(
            name='EMSDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('director_email', models.CharField(blank=True, max_length=100, null=True)),
                ('web_site', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name': 'EMS department',
            },
        ),
        migrations.CreateModel(
            name='FireDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'fire department',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('web_site', models.CharField(blank=True, max_length=90, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100, unique=True)),
                ('municode', models.IntegerField(blank=True, null=True)),
                ('cog', models.CharField(blank=True, max_length=100, null=True, verbose_name='COG')),
                ('congressional_district', models.SmallIntegerField(blank=True, null=True)),
                ('municipal_web_site', models.CharField(blank=True, max_length=100, null=True)),
                ('mayor', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_or_secretary', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('school_district', models.CharField(blank=True, max_length=100, null=True)),
                ('county_council_district', models.SmallIntegerField(blank=True, null=True)),
                ('municipal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_city', models.CharField(blank=True, max_length=50, null=True)),
                ('municipal_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='municipal ZIP code')),
            ],
            options={
                'verbose_name_plural': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='PGHCouncilDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_district', models.SmallIntegerField(unique=True)),
                ('committee', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('council_member', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pittsburgh council district',
                'verbose_name_plural': 'Pittsburgh council districts',
            },
        ),
        migrations.CreateModel(
            name='PoliceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chief_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('chief_email', models.CharField(blank=True, max_length=90, null=True)),
                ('web_site', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name': 'police department',
            },
        ),
        migrations.CreateModel(
            name='StateHouseDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.SmallIntegerField(unique=True)),
                ('rep_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('rep_home_county', models.CharField(blank=True, max_length=30, null=True)),
                ('rep_party', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'state House district',
            },
        ),
        migrations.CreateModel(
            name='StateSenateDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.SmallIntegerField(unique=True)),
                ('senator_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('senator_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('senator_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('senator_home_county', models.CharField(blank=True, max_length=30, null=True)),
                ('senator_party', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'state Senate district',
            },
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watershed_name', models.CharField(max_length=100, unique=True)),
                ('watershed_association', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'watershed',
            },
        ),
    ]
