# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='fire_department',
            field=models.ManyToManyField(blank=True, to='bitkeeper1.FireDepartment'),
        ),
    ]
