# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0003_municipality_police_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='police_department',
        ),
    ]
