# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0004_remove_municipality_police_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='police_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper1.PoliceDepartment'),
        ),
    ]
