# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0004_auto_20180213_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='policedepartment',
            name='web_site',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='policedepartment',
            name='chief_email',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='policedepartment',
            name='chief_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policedepartment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
