# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0005_auto_20180213_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'municipalities'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='manager_or_secretary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='cog',
            field=models.CharField(max_length=100, verbose_name='COG'),
        ),
    ]
