# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0005_municipality_police_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='state_house_district',
            field=models.ManyToManyField(blank=True, to='bitkeeper1.StateHouseDistrict', verbose_name='state House district'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state_senate_district',
            field=models.ManyToManyField(blank=True, to='bitkeeper1.StateSenateDistrict', verbose_name='state Senate district'),
        ),
    ]
