# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0006_auto_20180404_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='ems_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper1.EMSDepartment', verbose_name='EMS department'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='watershed',
            field=models.ManyToManyField(blank=True, to='bitkeeper1.Watershed'),
        ),
    ]
