# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0006_auto_20180213_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('director_email', models.CharField(blank=True, max_length=100, null=True)),
                ('web_site', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateHouseDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateSenateDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='school_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.Municipality'),
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.Municipality'),
        ),
        migrations.AddField(
            model_name='emsdepartment',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.Municipality'),
        ),
    ]
