# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0007_auto_20180213_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='policedepartment',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.Municipality'),
        ),
    ]
