# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper1', '0007_auto_20180404_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='emsdepartment',
            name='pittsburgh_council_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper1.PGHCouncilDistrict'),
        ),
        migrations.AddField(
            model_name='policedepartment',
            name='pittsburgh_council_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper1.PGHCouncilDistrict'),
        ),
    ]
