# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0008_policedepartment_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emsdepartment',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='policedepartment',
            name='municipality',
        ),
        migrations.AddField(
            model_name='municipality',
            name='ems_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.EMSDepartment'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='fire_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.FireDepartment'),
        ),
    ]
