# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0009_auto_20180213_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('web_site', models.CharField(blank=True, max_length=90, null=True)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='police_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PoliceDepartment'),
        ),
    ]
