# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0010_auto_20180213_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='ems_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.EMSDepartment'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='fire_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.FireDepartment'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='police_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PoliceDepartment'),
        ),
    ]
