# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0011_auto_20180214_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGHCouncilDistrict',
            fields=[
                ('council_district', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('committee', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('council_member', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PGH council districts',
            },
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'libraries'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='ems_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.EMSDepartment', verbose_name='EMS department'),
        ),
        migrations.AddField(
            model_name='emsdepartment',
            name='council_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PGHCouncilDistrict'),
        ),
        migrations.AddField(
            model_name='policedepartment',
            name='council_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PGHCouncilDistrict'),
        ),
    ]
