# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0012_auto_20180214_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emsdepartment',
            options={'verbose_name': 'EMS department'},
        ),
        migrations.AlterModelOptions(
            name='pghcouncildistrict',
            options={'verbose_name': 'PGH council district', 'verbose_name_plural': 'PGH council districts'},
        ),
        migrations.AddField(
            model_name='firedepartment',
            name='council_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PGHCouncilDistrict'),
        ),
    ]
