# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0013_auto_20180214_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firedepartment',
            name='council_district',
        ),
    ]
