# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0015_auto_20180214_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pghcouncildistrict',
            name='police_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.PoliceDepartment'),
        ),
    ]
