# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0016_pghcouncildistrict_police_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='county_council_district',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state_house_district',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state_senate_district',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
