# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0017_auto_20180215_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='municipal_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipal_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipal_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
