# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0018_auto_20180215_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watershed_name', models.CharField(max_length=100)),
                ('watershed_association', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='watershed',
            field=models.ManyToManyField(to='bitkeeper.Watershed'),
        ),
    ]
