# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0019_auto_20180215_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emsdepartment',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='firedepartment',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='policedepartment',
            old_name='city',
            new_name='address_city',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='watershed',
            field=models.ManyToManyField(blank=True, to='bitkeeper.Watershed'),
        ),
    ]
