# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0022_auto_20180223_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statesenatedistrict',
            name='municipality',
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='senator_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='senator_home_county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='senator_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='senator_party',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statesenatedistrict',
            name='senator_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state_senate_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.StateSenateDistrict', verbose_name='state Senate district'),
        ),
    ]
