# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0023_auto_20180306_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statehousedistrict',
            options={'verbose_name': 'state House district'},
        ),
        migrations.AlterModelOptions(
            name='statesenatedistrict',
            options={'verbose_name': 'state Senate district'},
        ),
        migrations.RemoveField(
            model_name='statehousedistrict',
            name='municipality',
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='rep_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='rep_home_county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='rep_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='rep_party',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statehousedistrict',
            name='rep_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state_house_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitkeeper.StateHouseDistrict', verbose_name='state House district'),
        ),
    ]
