# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0025_auto_20180306_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='cog',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='COG'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='congressional_district',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
