# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0026_auto_20180307_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='fire_department',
        ),
        migrations.AddField(
            model_name='municipality',
            name='fire_department',
            field=models.ManyToManyField(blank=True, to='bitkeeper.FireDepartment'),
        ),
    ]
