# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0027_auto_20180307_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='municipal_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='municipal ZIP code'),
        ),
        migrations.AlterField(
            model_name='statehousedistrict',
            name='district',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='statesenatedistrict',
            name='district',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
