# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0028_auto_20180313_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershed',
            name='watershed_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
