# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitkeeper', '0030_auto_20180314_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councilmember',
            options={'verbose_name': 'council member'},
        ),
        migrations.AlterModelOptions(
            name='firedepartment',
            options={'verbose_name': 'fire department'},
        ),
        migrations.AlterModelOptions(
            name='pghcouncildistrict',
            options={'verbose_name': 'Pittsburgh council district', 'verbose_name_plural': 'Pittsburgh council districts'},
        ),
        migrations.AlterModelOptions(
            name='policedepartment',
            options={'verbose_name': 'police department'},
        ),
        migrations.AlterModelOptions(
            name='watershed',
            options={'verbose_name': 'watershed'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='municode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
